name: CI
on: push
jobs:
  helloworld-linux:
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo "Hello, World!"

  helloworld-windows:
    runs-on: windows-latest
    steps:
      - name: HelloWorld
        run: echo "Hello, World"