name: CI
on: push
jobs:
  helloworld-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: HelloWorld
        run: echo "Hello, World!"
      - name: LS
        run: ls

  helloworld-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: HelloWorld
        run: echo "Hello, World"
      - name: LS
        run: dir